### ISSUE TITLE
are you planning to update to new jquery api?

### ISSUE THREAD

**Issue by t0lkman** [futurecolors/jqapi.ru#6] opened 2016-02-01 20:23 UTC
are you planning to update to new jquery api? 1.12.0/2.2.0

**Comment by coagulant** [comment] 2016-02-02 05:43
I guess no, but feel free to send patches

**Comment by amalitsky** [comment] 2017-02-15 01:22
Duplicate of #1 in a sense that will be great to support recent versions

**Closed by amalitsky** 2017-02-15 01:22 UTC
Labels: duplicate
